on:
 schedule:
   - cron: '* * * * *'
 pull_request:
   types: [opened, synchronize, reopened, closed]

name: Update packages
jobs:
 release:
   name: Update Python Packages
   runs-on: ubuntu-latest
   steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Update pip packages
        uses: technote-space/create-pr-action@v2
        with:
          EXECUTE_COMMANDS: |
            pip install pip-upgrader
            pip-upgrade requirements.txt -p all --skip-package-installation
          COMMIT_MESSAGE: 'update pip dependencies'
          COMMIT_NAME: 'GitHub Actions'
          COMMIT_EMAIL: 'example@example.com'
          PR_BRANCH_NAME: 'chore-pip-update-${PR_ID}'
          PR_TITLE: 'Bot: update pip dependencies'
